"""
MQTT Topic hierarchy taxonomy for the ICSC testbed.
"""

from core.config import (
    TOPIC_AUTH_LOGIN,
    TOPIC_AUTH_EVENTS,
    TOPIC_COMMANDS,
    TOPIC_COMMAND_ACKS,
    TOPIC_CONTROL_EVENTS,
    TOPIC_TELEMETRY,
    TOPIC_PLANT_STATE,
    TOPIC_PLANT_EVENTS,
    TOPIC_ALERTS,
    TOPIC_SECURITY_EVENTS,
    TOPIC_AUDIT_EVENTS,
    LEGACY_TOPIC_TELEMETRY,
    LEGACY_TOPIC_COMMANDS,
    LEGACY_TOPIC_ALERTS,
)
